# Generated by Django 5.0 on 2024-01-02 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_usr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='usr',
        ),
    ]
