# Generated by Django 5.0 on 2024-01-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=3),
        ),
    ]
