# Generated by Django 5.0 on 2024-01-07 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listing_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='usr',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
