# Generated by Django 5.0 on 2024-01-09 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='usr',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_usr', to=settings.AUTH_USER_MODEL),
        ),
    ]
